name: Production

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - Deploying
jobs:
  run-DevOps_Project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Configure kubectl
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: install EKS
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
          eksctl version
          kubectl get nodes -o wide
      

      - name: Create kubeconfig
        run: eksctl create cluster --name demo-cluster --region us-east-1 
      

      
      - name: run Deployment
        run: kubectl apply -f ./k8s/manifests/deployment.yml

      - name: run service 
        run : kubectl apply -f ./k8s/manifests/service.yml
      - name: run ingress
        run: kubectl apply -f ./k8s/manifests/ingress.yml
      - name: Run EKS Cluster
        run:  |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/aws/deploy.yaml
          kubectl get ing