name: Production

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - Deploying
jobs:
  run-DevOps_Project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run EKS Cluster
        run:  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/aws/deploy.yaml


      
      - name: run Deployment
        run: kubectl apply -f deployment.yml

      - name: run service 
        run : kubectl apply -f service.yml
      - name: run ingress
        run: kubectl apply -f ingress.yml